/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    "grid-cols-7",
    "grid",
    "min-h-120",
    "min-h-240",
    "min-h-[100px]",
    "min-h-[120px]",
    "min-h-[240px]",
    // Spacing classes
    "ml-4",
    "mr-4",
    "mt-4",
    "mb-4",
    "mx-4",
    "my-4",
    "m-4",
    "pl-4",
    "pr-4",
    "pt-4",
    "pb-4",
    "px-4",
    "py-4",
    "p-4",
    "ml-2",
    "mr-2",
    "mt-2",
    "mb-2",
    "mx-2",
    "my-2",
    "m-2",
    "pl-2",
    "pr-2",
    "pt-2",
    "pb-2",
    "px-2",
    "py-2",
    "p-2",
    "ml-6",
    "mr-6",
    "mt-6",
    "mb-6",
    "mx-6",
    "my-6",
    "m-6",
    "pl-6",
    "pr-6",
    "pt-6",
    "pb-6",
    "px-6",
    "py-6",
    "p-6",
    "ml-3",
    "mr-3",
    "mt-3",
    "mb-3",
    "mx-3",
    "my-3",
    "m-3",
    "pl-3",
    "pr-3",
    "pt-3",
    "pb-3",
    "px-3",
    "py-3",
    "p-3",
    "ml-5",
    "mr-5",
    "mt-5",
    "mb-5",
    "mx-5",
    "my-5",
    "m-5",
    "pl-5",
    "pr-5",
    "pt-5",
    "pb-5",
    "px-5",
    "py-5",
    "p-5",
  ],
  theme: {
    extend: {
      gridTemplateColumns: {
        7: "repeat(7, minmax(0, 1fr))",
      },
      minHeight: {
        240: "240px",
        120: "120px",
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [],
  corePlugins: {
    preflight: true,
  },
  experimental: {
    optimizeUniversalDefaults: true,
  },
};
